---
functional:
  - Пользователь должен иметь возможность искать товары по ключевому слову или категории
  - Пользователь должен иметь возможность просматривать товары, пользуясь постраничным выводом
  - Пользователь должен иметь возможность фильтровать товары
  - Пользователь должен иметь возможность просматривать товары и просматривать подробную информацию о товаре (название, рейтинг, цена со скидкой и без нее) на странице товара и в каталоге
  - Пользователь должен иметь возможность добавлять товар в корзину и продолжать выбирать товары в каталоге
  - Пользователь должен иметь возможность добавлять товары в корзину и просматривать содержимое корзины
  - Пользователь должен иметь возможность на странице корзины удалить товар из корзины, продолжить выбирать товары в каталоге, оформить заказ с переходом на страницу оплаты
non-functional:
  - Сайт нужно разработать с учетом удобства использования и оптимизировать для скорости работы
  - Сайт должен быть безопасным и защищать данные пользователя
  - Сайт должен иметь мобильную версию и быть адаптивным
  - Сайт нужно протестировать на совместимость с последними версиями браузеров
  - Важно, чтобы сайт мог обрабатывать большое количество трафика
  - Сайт должен быть доступен на различных устройствах
  - Сайт должен хранить корзину в сессии браузера
  - Сайт должен быть SPA-прилолжением
implicit:
  - Пользователь не должен иметь возможности добавлять в корзину товара больше, чем есть в наличии
  - Пользователь не должен иметь возможности добавлять в корзину товары, которых нет в наличии
  - Сайт должен иметь возможность интеграции с платежными системами
  - Формула на странице корзины должна правильно считать сумму заказа
  - Информация на главной странице товара должна совпадать с информацией на карточке товара
  - Все варианты фильтрации должны распространяться на все страницы товаров
  - Пользователь должен иметь возможность сброса фильтров
  - Сайт должен быть интуитивно понятным и удобным в использовании для пользователя
  - Визуальный дизайн сайта должен быть современным и привлекательным
  - Ошибки при работе с сайтом должны быть обработаны с выводом понятных сообщений пользователю
  - Уведомления и подтверждения действий (например, добавление товара в корзину) должны быть реализованы через всплывающие окна или визуальные индикаторы
  - Сайт должен иметь интуитивно понятную и простую навигацию по всем страницам сайта
